export const EnvironmentVariableNames = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  APP_NAME: 'APP_NAME',

  GRAPHQL_PATH: 'GRAPHQL_PATH',
  GRAPHQL_SORT_SCHEMA: 'GRAPHQL_SORT_SCHEMA',
  GRAPHQL_INTROSPECTION: 'GRAPHQL_INTROSPECTION',

  NOTIFICATIONS_DEFAULT_CHANNEL: 'NOTIFICATIONS_DEFAULT_CHANNEL',

  BULLMQ_EMAIL_VERIFICATION_QUEUE: 'BULLMQ_EMAIL_VERIFICATION_QUEUE',
  BULLMQ_CHANGE_EMAIL_QUEUE: 'BULLMQ_CHANGE_EMAIL_QUEUE',
  BULLMQ_PASSWORD_CHANGED_QUEUE: 'BULLMQ_PASSWORD_CHANGED_QUEUE',
  BULLMQ_RESET_PASSWORD_QUEUE: 'BULLMQ_RESET_PASSWORD_QUEUE',
  BULLMQ_SET_FIRST_PASSWORD_QUEUE: 'BULLMQ_SET_FIRST_PASSWORD_QUEUE',
  BULLMQ_WELCOME_QUEUE: 'BULLMQ_WELCOME_QUEUE',

  RATE_LIMITER_DEFAULT_TTL: 'RATE_LIMITER_DEFAULT_TTL',
  RATE_LIMITER_DEFAULT_LIMIT: 'RATE_LIMITER_DEFAULT_LIMIT',
  LOGIN_RATE_LIMITER_DEFAULT_TTL: 'LOGIN_RATE_LIMITER_DEFAULT_TTL',
  LOGIN_RATE_LIMITER_DEFAULT_LIMIT: 'LOGIN_RATE_LIMITER_DEFAULT_LIMIT',
  FORGET_PASSWORD_RATE_LIMITER_DEFAULT_TTL: 'FORGET_PASSWORD_RATE_LIMITER_DEFAULT_TTL',
  FORGET_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT: 'FORGET_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT',
  VERIFY_RESET_PASSWORD_RATE_LIMITER_DEFAULT_TTL: 'VERIFY_RESET_PASSWORD_RATE_LIMITER_DEFAULT_TTL',
  VERIFY_RESET_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT: 'VERIFY_RESET_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT',
  VERIFY_SET_FIRST_PASSWORD_RATE_LIMITER_DEFAULT_TTL: 'VERIFY_SET_FIRST_PASSWORD_RATE_LIMITER_DEFAULT_TTL',
  VERIFY_SET_FIRST_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT: 'VERIFY_SET_FIRST_PASSWORD_RATE_LIMITER_DEFAULT_LIMIT',
  
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_NAME: 'DB_NAME',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_MIGRATIONS: 'DB_MIGRATIONS',
  DB_ENTITIES: 'DB_ENTITIES',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_USERNAME: 'REDIS_USERNAME',
  REDIS_PASSWORD: 'REDIS_PASSWORD',

  ACCESS_TOKEN_SECRET_KEY: 'ACCESS_TOKEN_SECRET_KEY',
  ACCESS_TOKEN_EXPIRATION_DURATION: 'ACCESS_TOKEN_EXPIRATION_DURATION',

  REFRESH_TOKEN_EXPIRATION_DURATION: 'REFRESH_TOKEN_EXPIRATION_DURATION',
  EMAIL_VERIFICATION_TOKEN_EXPIRATION_DURATION: 'EMAIL_VERIFICATION_TOKEN_EXPIRATION_DURATION',
  RESET_PASSWORD_TOKEN_EXPIRATION_DURATION: 'RESET_PASSWORD_TOKEN_EXPIRATION_DURATION',

  EMAIL_PROVIDER_HOST: 'EMAIL_PROVIDER_HOST',
  EMAIL_PROVIDER_PORT: 'EMAIL_PROVIDER_PORT',
  EMAIL_PROVIDER_USERNAME: 'EMAIL_PROVIDER_USERNAME',
  EMAIL_PROVIDER_PASSWORD: 'EMAIL_PROVIDER_PASSWORD',

  DASHBOARD_ORIGIN: 'DASHBOARD_ORIGIN',
  DASHBOARD_RESET_PASSWORD_ROUTE: 'DASHBOARD_RESET_PASSWORD_ROUTE',
  DASHBOARD_SET_PASSWORD_ROUTE: 'DASHBOARD_SET_PASSWORD_ROUTE',
  DASHBOARD_CHANGE_EMAIL_ROUTE: 'DASHBOARD_CHANGE_EMAIL_ROUTE',

  MAIN_APP_ORIGIN: 'MAIN_APP_ORIGIN',
  MAIN_APP_RESET_PASSWORD_ROUTE: 'MAIN_APP_RESET_PASSWORD_ROUTE',
  MAIN_APP_EMAIL_VERIFICATION_ROUTE: 'MAIN_APP_EMAIL_VERIFICATION_ROUTE',
  MAIN_APP_CHANGE_EMAIL_ROUTE: 'MAIN_APP_CHANGE_EMAIL_ROUTE',
  MAIN_APP_OAUTH_CALLBACK_URL: 'MAIN_APP_OAUTH_CALLBACK_URL',

  AWS_S3_BUCKET: 'AWS_S3_BUCKET',
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_ACCESS_KEY_ID: 'AWS_S3_ACCESS_KEY_ID',
  AWS_S3_SECRET_ACCESS_KEY: 'AWS_S3_SECRET_ACCESS_KEY',

  STORAGE_IMAGE_PROFILE_IMAGES_DIR: 'STORAGE_IMAGE_PROFILE_IMAGES_DIR',
  STORAGE_IMAGE_PROFILE_IMAGES_MAX_SIZE: 'STORAGE_IMAGE_PROFILE_IMAGES_MAX_SIZE',

  GOOGLE_OAUTH_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID',
  GOOGLE_OAUTH_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
  GOOGLE_OAUTH_CALLBACK_URL: 'GOOGLE_OAUTH_CALLBACK_URL',
  GOOGLE_OAUTH_SCOPE: 'GOOGLE_OAUTH_SCOPE',
};
